global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'localhost:9100'

remote_write:
  - url: "http://admin-server:9090/write"
remote_read:
  - url: "http://admin-server:9090/read"

